-- Attempt on Unified Data Base, based on XWS (dropped after w1, too much hassle) and FFG conversion table
masterShipDB = {}
masterShipDB[0] = {
    ['name'] = '',
    ['hull'] = 0,
    ['shield'] = 0,
    ['size'] = 'small',
    ['agility'] = 1,
    ['energy'] = 0,
    ['factions'] = { ['dummy'] = true },
    ['arcs'] = { fixed = { range = 3, type = { 'front' } } }
}

masterShipDB['yt2400lightfreighter2023'] = {
    name = 'YT-2400',
    hull = 6,
    shield = 4,
    size = 'large',
    proximity_hider = true,
    agility = 2,
    textures = {
        standard =
        'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/large/yt2400lightfreighter/Textures/standard.jpg',
    },
    factions = { ['rebelalliance'] = true, ['scumandvillainy'] = true },
    arcs = { turret = { main = { name = 'primary', type = { 'doubleturret' } } } },
    mesh =
    'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/large/yt2400lightfreighter/yt2400.obj',
    move_set = { 'wtl1', 'bbl1', 'bs1', 'bbr1', 'wtr1', 'wtl2', 'wbl2', 'bs2', 'wbr2', 'wtr2', 'wtl3', 'wbl3', 'ws3', 'wbr3', 'wtr3', 'ws4', 'rk4' },
    keywords = { 'Freighter' }
}

return masterShipDB
