-- ~~~~~~
-- Script by dzikakulka
-- Issues, history at: http://github.com/tjakubo2/TTS_lib
--
-- Misc functions for extending Lua functionality
-- Description and usage in README.md in this lib folder in repository
-- ~~~~~~

-- TODO: DELETE ME Please! Nothing is using this, but it must be required by the save file.
math = require("TTS_Lib.Util.Math")
table = require("TTS_Lib.Util.Table")
string = require("TTS_Lib.Util.String")
