-- ~~~~~~
-- Script by dzikakulka
-- Issues, history at: http://github.com/tjakubo2/TTS_lib
--
-- Misc functions for extending Lua functionality
-- Description and usage in README.md in this lib folder in repository
-- ~~~~~~

if not package.loaded['Util'] then
    package.loaded['Util'] = true

math = require('TTS_Lib.Util.Math')
table = require('TTS_Lib.Util.Table')
string = require('TTS_Lib.Util.String')

end
