

-- Attempt on Unified Data Base, based on XWS (dropped after w1, too much hassle) and FFG conversion table
masterShipDB={}
masterShipDB[0]={['name']='',['Hull']=0,['Shield']=0,['size']='small',['agi']=1,['Energy']=0,['XWS']='',['Fac']={[0]=true},['arcs']={fixed = { range=3, type = {'front'}}}}

masterShipDB['modifiedyt1300lightfreighter']={
    name = 'Modified YT-1300',
    Hull = 8,
    Shield = 5,
    size = 'large',
    ProximityHider = true,
    agi = 1,
    XWS = 'modifiedyt1300lightfreighter',
    newSpawner = true,
    textures = {
      standard = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/large/modifiedyt1300lightfreighter/textures/standard.jpg',
    },
    Fac = {[1]=true},
    arcs = {turret = {main = {name = 'primary', type={'doubleturret'}}}},
    mesh = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/large/modifiedyt1300lightfreighter/rebel_falcon.obj',
    moveSet = {'wbl1','bs1','wbr1','wtl2','bbl2','bs2','bbr2','wtr2','rbl3s','wtl3','wbl3','bs3','wbr3','wtr3','rbr3s','ws4','rk4'},
    keywords = {'Freighter', 'YT-1300'}
}

masterShipDB['starviperclassattackplatform']={
    name = 'StarViper',
    Hull = 4,
    Shield = 1,
    size = 'small',
    agi = 3,
    XWS = 'starviperclassattackplatform',
    newSpawner = true,
    textures = {
      red = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/small/starviperclassattackplatform/textures/blacksunassassin.png',
      white = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/small/starviperclassattackplatform/textures/blacksunenforcer.png',
    },
    Fac = {[3]=true},
    arcs = {fixed = { range=3, type = {'front'}}},
    mesh = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/Small/starviperclassattackplatform/starviper.obj',
    moveSet = {'wtl1','bbl1','bs1','bbr1','wtr1','wtl2','bbl2','bs2','bbr2','wtr2','rbl3s','wbl3','bs3','wbr3','rbr3s','ws4' }
}

masterShipDB['scurrgh6bomber']={
    name = 'Scurrg H6 Bomber',
    Hull = 6,
    Shield = 4,
    size = 'medium',
    agi = 1,
    XWS = 'scurrgh6bomber',
    newSpawner = true,
    textures = {
      orange = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/medium/scurrgh6bomber/textures/orange.jpg', 
    },
      red = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/medium/scurrgh6bomber/textures/red.jpg', 
    },
    Fac = {[3]=true},
    arcs = {fixed = { range=3, type = {'front'}}},
    mesh = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/scurrgh6bomber/scurrg.obj',
    moveSet = {'bbl1','bs1','bbr1','wtl2','wbl2','bs2','wbr2','wtr2','rtl3t','rtl3','wbl3','ws3','wbr3','rtr3','rtr3t','rs4'}
}

masterShipDB['yt2400lightfreighter']={
    name = 'YT-2400',
    Hull = 6,
    Shield = 4,
    size = 'large',
    ProximityHider = true,
    agi = 2,
    XWS = 'yt2400lightfreighter',
    newSpawner = true,
    textures = {
      standard = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/large/yt2400lightfreighter/textures/standard.jpg',
    },
    Fac = {[1]=true},
    arcs = {turret = {main = {name = 'primary', type={'doubleturret'}}}},
    mesh = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/Large/yt2400lightfreighter/yt2400.obj',
    moveSet = {'wtl1','bbl1','bs1','bbr1','wtr1','wtl2','wbl2','bs2','wbr2','wtr2','wtl3','wbl3','ws3','wbr3','wtr3','ws4','rk4'},
    keywords = {'Freighter'}
}

masterShipDB['auzituckgunship']={
    name = 'Auzituck Gunship',
    Hull = 6,
    Shield = 2,
    size = 'small',
    agi = 1,
    XWS = 'auzituckgunship',
    newSpawner = true,
    textures = {
      orange = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/small/auzituckgunship/textures/orange.jpg',
      cream = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/small/auzituckgunship/textures/cream.jpg',
    },
    Fac = {[1]=true},
    arcs = {fixed = { range=3, type = {'fullfront'}}},
    mesh = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/Small/auzituckgunship/auzituck.obj',
    moveSet = {'bbl1', 'bs1', 'bbr1','wtl2','wbl2','bs2','wbr2','wtr2','wtl3','wbl3','bs3','wbr3','wtr3','ws4','rs0'}
}

masterShipDB['kihraxzfighter']={
    name = 'Khiraxz Fighter',
    Hull = 5,
    Shield = 1,
    size = 'small',
    agi = 2,
    XWS = 'kihraxzfighter',
    newSpawner = true,
    textures = {
      standard = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/small/kihraxzfighter/textures/standard.jpg',
      green = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/small/kihraxzfighter/textures/green.jpg',
      orange = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/small/kihraxzfighter/textures/orange.jpg',
      blacksun = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/small/kihraxzfighter/textures/blacksun.jpg',
      talonbane = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/small/kihraxzfighter/textures/talonbane.jpg',
    },
    Fac = {[3]=true},
    arcs = {fixed = { range=3, type = {'front'}}},
    mesh = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/Small/kihraxzfighter/khiraxz.obj',
    moveSet = {'wtl1','bbl1','bbr1','wtr1','rtl2t','wtl2','bbl2','bs2','bbr2','wtr2','rtr2t','wbl3','bs3','wbr3','ws4','rk4'}
}

masterShipDB['sheathipedeclassshuttle']={
    name = 'Sheathipede Shuttle',
    Hull = 3,
    Shield = 1,
    size = 'small',
    agi = 2,
    XWS = 'sheathipedeclassshuttle',
    newSpawner = true,
    textures = {
      standard = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/small/sheathipedeclassshuttle/textures/standard.jpg',
    },
    Fac = {[1]=true},
    arcs = {fixed = { range=3, type = {'frontback'}}},
    mesh = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/Small/sheathipedeclassshuttle/sheathipede.obj',
    moveSet = {'rs1r','wbl1','bs1','wbr1','wtl2','bbl2','bs2','bbr2','wtr2','rtl3','wbl3','bs3','wbr3','rtr3','rk3','rs4'}
}

masterShipDB['quadrijettransferspacetug']={
    name = 'Quad Jumper',
    Hull = 6,
    Shield = 0,
    size = 'small',
    agi = 2,
    XWS = 'quadrijettransferspacetug',
    newSpawner = true,
    textures = {
      standard = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/small/quadrijettransferspacetug/textures/standard.jpg',
    },
    Fac = {[3]=true},
    arcs = {fixed = { range=3, type = {'front'}}},
    mesh = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/Small/quadrijettransferspacetug/quadjumper.obj',
    moveSet = {'rbl1r','rbr1r','wtl1','wbl1','ws1','wbr1','wtr1','rs2r','rbl2s','wtl2','bbl2','bs2','bbr2','wtr2','rbr2s','wbl3','bs3','wbr3'}
}

masterShipDB['firesprayclasspatrolcraft']={
    name = 'FireSpray',
    Hull = 6,
    Shield = 4,
    size = 'medium',
    agi = 2,
    XWS = 'firesprayclasspatrolcraft',
    newSpawner = true,
    textures = {
      bountyhunter = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/medium/firesprayclasspatrolcraft/textures/bountyhunter.jpg', 
      boba = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/medium/firesprayclasspatrolcraft/textures/bobafett.jpg', 
      emon = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/medium/firesprayclasspatrolcraft/textures/emonazzameen.jpg', 
      jango = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/medium/firesprayclasspatrolcraft/textures/jangofett.jpg', 
      kath = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/medium/firesprayclasspatrolcraft/textures/kathscarlet.jpg', 
      koshka = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/medium/firesprayclasspatrolcraft/textures/koshkafrost.jpg', 
      krassis = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/medium/firesprayclasspatrolcraft/textures/krassistrelix.jpg', 
      zam = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/medium/firesprayclasspatrolcraft/textures/zamwesell.jpg', 
    },
    Fac = {[3]=true, [7]=true},
    arcs = {fixed = { range=3, type = {'frontback'}}},
    mesh = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/Medium/firesprayclasspatrolcraft/firespray.obj',
    moveSet = {'wtl1','bbl1','bs1','bbr1','wtr1','wtl2','wbl2','bs2','wbr2','wtr2','rtl3t','wbl3','bs3','wbr3','rtr3t','ws4','rk4'}
}

masterShipDB['tielnfighter']={
    name = 'TIE/ln Fighter',
    Hull = 3,
    Shield = 0,
    size = 'small',
    agi = 3,
    XWS = 'tielnfighter',
    newSpawner = true,
    textures = {
      blue = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/small/tielnfighter/textures/Tie-Fighter-Blue2.jpg',
      grey = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/small/tielnfighter/textures/Tie-Fighter-Grey2.jpg',
      inferno = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/small/tielnfighter/textures/Tie-Fighter-Inferno2.jpg',
      rebel = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/small/tielnfighter/textures/Tie-Fighter-Rebel.jpg',
    },
    Fac = {[1]=true,[2]=true},
    arcs = {fixed = { range=3, type = {'front'}}},
    mesh = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/small/tielnfighter/TIE_LN.obj',
    moveSet = {'wtl1','wtr1','wtl2','bbl2','bs2','bbr2','wtr2','wtl3','wbl3','bs3','wbr3','wtr3','rk3','ws4','rk4','ws5'},
    keywords = {"TIE"}
}

masterShipDB['btla4ywing']={
    name = 'Y-Wing',
    Hull = 6,
    Shield = 2,
    size = 'small',
    agi = 1,
    XWS = 'btla4ywing',
    newSpawner = true,
    textures = {
      gold = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/small/btla4ywing/textures/gold.png',
      grey = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/small/btla4ywing/textures/grey.png',
      horton = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/small/btla4ywing/textures/hortonsalm.png',
      norra = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/small/btla4ywing/textures/norrawexley.png',
    },
    Fac = {[1]=true,[3]=true},
    arcs = {fixed = { range=3, type = {'front'}}},
    mesh = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/Small/btla4ywing/btla4_ywing.obj',
    moveSet = {'bbl1', 'bs1', 'bbr1','wtl2','wbl2','bs2','wbr2','wtr2','rtl3','wbl3','ws3','wbr3','rtr3','rs4','rk4'},
    keywords = {'Y-Wing'}
}

masterShipDB['tieadvancedx1']={
    name = 'TIE Advanced x1',
    Hull = 3,
    Shield = 2,
    size = 'small',
    agi = 3,
    XWS = 'tieadvancedx1',
    newSpawner = true,
    textures = {
      blue = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/small/tieadvancedx1/textures/tieadvancedx1blue.jpg',
      grey= 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/small/tieadvancedx1/textures/tieadvancedx1grey.jpg',
    },
    Fac = {[2]=true},
    arcs = {fixed = { range=3, type = {'front'}}},
    mesh = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/Small/tieadvancedx1/tieadvancedx1.obj',
    moveSet = {'bbl1','ws1','bbr1','wtl2','bbl2','bs2','bbr2','wtr2','rtl3t','wtl3','wbl3','bs3','wbr3','wtr3','rtr3t','ws4','rk4','ws5'},
    keywords = {'TIE'}
}

masterShipDB['alphaclassstarwing']={
    name = 'Alpha Class StarWing',
    Hull = 4,
    Shield = 3,
    size = 'small',
    agi = 2,
    XWS ='alphaclassstarwing',
    newSpawner = true,
    textures = {
      standard = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/small/alphaclassstarwing/textures/standard.jpg',
    },
    Fac = {[2]=true},
    arcs = {fixed = { range=3, type = {'front'}}},
    mesh = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/Small/alphaclassstarwing/starwing.obj',
    moveSet = {'wbl1','bs1','wbr1','wtl2','bbl2','bs2','bbr2','wtr2','wtl3','wbl3','ws3','wbr3','wtr3','rs4'}
}

masterShipDB['ut60duwing']={
    name = 'U-Wing',
    Hull = 5,
    Shield = 3,
    size = 'medium',
    agi = 2,
    XWS = 'ut60duwing',
    newSpawner = true,
    textures = {
      standard = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/medium/ut60duwing/textures/standard.jpg', 
      captain = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/medium/ut60duwing/textures/captain.jpg', 
      renegade = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/medium/ut60duwing/textures/renegade.jpg', 
    },
    Fac = {[1]=true},
    arcs = {fixed = { range=3, type = {'front'}}},
    moveSet = {'bbl1', 'bs1', 'bbr1', 'wtl2', 'bbl2', 'bs2', 'bbr2', 'wtr2','wbl3','ws3','wbr3','ws4','rs0'},
    mesh = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/medium/ut60duwing/UWing_Base.obj',
    Config = {
      States = {
        [1] = {
            Name = "Pivot Wing (Open)",
            Model = "https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/medium/ut60duwing/UWing_Open.obj",
            ZRot = 0,
            Message = " opened their wings.",
        },
        [2] = {
            Name = "Pivot Wing (Closed)",
            Model = "https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/medium/ut60duwing/UWing_Close.obj",
            ZRot = 180,
            Message = " closed their wings.",
        }
      },
      ContextText = "Open/Close pivot wings",
      Token = "http://nnxwing.com/Content/TTS/Config/UWing.png"
    }
}

masterShipDB['tieskstriker']={
  name = 'TIE/sk Striker',
  Hull = 4,
  Shield = 0,
  size = 'small',
  agi = 2,
  XWS = 'tieskstriker',
    newSpawner = true,
    textures = {
      blue = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/small/tieskstriker/textures/tieskstrikerblue.jpg',
      grey = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/small/tieskstriker/textures/tieskstrikergrey.jpg',
    },
  Fac = {[2]=true},
  arcs = {fixed = { range=3, type = {'front'}}},
  moveSet = {'wtl1','bbl1','bs1','bbr1','wtr1','rk1','rbl2s','wtl2','bbl2','bs2','bbr2','wtr2','rbr2s','wbl3','bs3','wbr3'},
  mesh = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/Small/tieskstriker/tiestriker.obj',
  keywords = {'TIE'}
}

masterShipDB['asf01bwing']={
  name = 'B-Wing',
  Hull = 4,
  Shield = 4,
  size = 'small',
  agi = 1,
  XWS = 'asf01bwing',
  Fac = {[1]=true},
  arcs = {fixed = { range=3, type = {'front'}}},
  moveSet = {'rtl1t','rtl1','bbl1','bs1','bbr1','rtr1','rtr1t','wtl2','wbl2','bs2','wbr2','wtr2','rk2','rbl3','bs3','rbr3','rs4'},
  mesh = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/Small/REB_bwing/bwing-base.obj',
  keywords = {'B-Wing'},
  Config = {
    States = {
      [1] = {
          Name = "S-Foils (Open)",
          Model = "https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/Small/REB_bwing/bwing-open.obj",
          ZRot = 0,
          Message = " opened their S-Foils.",
      },
      [2] = {
          Name = "S-Foils (Closed)",
          Model = "https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/Small/REB_bwing/bwing-closed.obj",
          ZRot = 180,
          Message = " closed their S-Foils.",
      }
    },
    ContextText = "Open/Close S-Foils",
    Token = "http://nnxwing.com/Content/TTS/Config/BWing.png"
  }
}

masterShipDB['tiededefender']={
  name = 'TIE/de Defender',
  Hull = 3,
  Shield = 4,
  size = 'small',
  agi = 3,
  XWS = 'tiededefender',
    newSpawner = true,
    textures = {
      blue = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/small/tiededefender/textures/tiededefenderblue.jpg',
      grey = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/small/tiededefender/textures/tiededefendergrey.jpg',
      red = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/small/tiededefender/textures/tiededefenderred.jpg',
      skystrike = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/small/tiededefender/textures/tiededefenderss.jpg',
      vader = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/small/tiededefender/textures/tiededefendervader.jpg',
      kyber = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/small/tiededefender/textures/Kyber.jpg',
    },
  Fac = {[2]=true},
  arcs = {fixed = { range=3, type = {'front'}}},
  moveSet = {'rtl1','bbl1','bbr1','rtr1','rtl2','wbl2','bs2','wbr2','rtr2','rk2','wtl3','wbl3','bs3','wbr3','wtr3','bs4','wk4','bs5'},
  mesh = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/Small/tiededefender/defender.obj',
  keywords = {'TIE'}
}

masterShipDB['tiesabomber']={
  name = 'TIE/sa Bomber',
  Hull = 6,
  Shield = 0,
  size = 'small',
  agi = 2,
  XWS = 'tiesabomber',
    newSpawner = true,
    textures = {
      blue = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/small/tiesabomber/textures/tiesabomberblue.jpg',
      grey = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/small/tiesabomber/textures/tiesabombergrey.jpg',
    },
  Fac = {[2]=true},
  arcs = {fixed = { range=3, type = {'front'}}},
  moveSet = {'wbl1','bs1','wbr1','wtl2','bbl2','bs2','bbr2','wtr2','wtl3','wbl3','bs3','wbr3','wtr3','rk3','ws4','rk5'},
  mesh = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/Small/tiesabomber/tiebomber.obj',
  keywords = {'TIE'}
}

masterShipDB['tiecapunisher']={
  name = 'TIE/ca Punisher',
  Hull = 6,
  Shield = 3,
  size = 'medium',
  agi = 1,
  XWS = 'tiecapunisher',
    newSpawner = true,
    textures = {
      blue = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/medium/tiecapunisher/textures/tiecapunisherblue.jpg', 
      grey = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/medium/tiecapunisher/textures/tiecapunishergrey.jpg',
    },
  Fac = {[2]=true},
  arcs = {fixed = { range=3, type = {'front'}}},
  moveSet = {'bbl1','bs1','bbr1','wtl2','wbl2','bs2','wbr2','wtr2','rtl3','wbl3','ws3','wbr3','rtr3','rk4','rs0'},
  mesh = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/Medium/tiecapunisher/tiepunisher.obj',
  keywords = {'TIE'}
}

masterShipDB['aggressorassaultfighter']={
  name = 'Aggressor',
  Hull = 5,
  Shield = 3,
  size = 'medium',
  agi = 3,
  XWS = 'aggressorassaultfighter',
    newSpawner = true,
    textures = {
      standard = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/medium/aggressorassaultfighter/textures/standard.jpg', 
    },
  Fac = {[3]=true},
  arcs = {fixed = { range=3, type = {'front'}}},
  moveSet = {'wtl1','bbl1','bs1','bbr1','wtr1','wtl2','bbl2','bs2','bbr2','wtr2','rbl3s','bbl3','bs3','bbr3','rbr3s','ws4','rk4'},
  mesh = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/Medium/aggressorassaultfighter/aggressor.obj'
}

masterShipDB['g1astarfighter']={
  name = 'G-1A StarFighter',
  Hull = 5,
  Shield = 4,
  size = 'medium',
  agi = 1,
  XWS = 'g1astarfighter',
    newSpawner = true,
    textures = {
      standard = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/medium/g1astarfighter/textures/standard.jpg', 
    },
  Fac = {[3]=true},
  arcs = {fixed = { range=3, type = {'front'}}},
  moveSet = {'rtl1','bbl1','bs1','bbr1','rtr1','wtl2','wbl2','bs2','wbr2','wtr2','rk2','rbl3','ws3','rbr3','rs4','rk4','rs0'},
  mesh = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/Medium/g1astarfighter/g1a.obj'
}

masterShipDB['vcx100lightfreighter']={
  name = 'VCX-100',
  Hull = 10,
  Shield = 4,
  size = 'large',
  ProximityHider = true,
  agi = 0,
  XWS = 'vcx100lightfreighter',
    newSpawner = true,
    textures = {
      standard = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/large/vcx100lightfreighter/textures/standard.jpg',
    },
  Fac = {[1]=true},
  arcs = {fixed = { range=3, type = {'front'}}},
  Docking = true,
  moveSet = {'rtl1','wbl1','bs1','wbr1','rtr1','wtl2','bbl2','bs2','bbr2','wtr2','rtl3','wbl3','ws3','wbr3','rtr3','ws4','rk4'},
  mesh = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/Large/vcx100lightfreighter/vcx100.obj',
  keywords = {'Freighter'}
}

masterShipDB['yv666lightfreighter']={
  name = 'YV-666',
  Hull = 9,
  Shield = 3,
  size = 'large',
  ProximityHider = true,
  agi = 1,
  XWS = 'yv666lightfreighter',
    newSpawner = true,
    textures = {
      standard = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/large/yv666lightfreighter/textures/standard.jpg',
    },
  Fac = {[3]=true},
  arcs = {fixed = { range=3, type = {'fullfront'}}},
  moveSet = {'bbl1','bs1','bbr1','rtl2','wbl2','bs2','wbr2','rtr2','wtl3','wbl3','bs3','wbr3','wtr3','ws4','rs0'},
  mesh = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/Large/yv666lightfreighter/yv666.obj',
  keywords = {'Frighter'}
}

masterShipDB['tieadvancedv1']={
  name = 'TIE Advanced v1',
  Hull = 2,
  Shield = 2,
  size = 'small',
  agi = 3,
  XWS = 'tieadvancedv1',
    newSpawner = true,
    textures = {
      blue = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/small/tieadvancedv1/textures/tieadvancedv1blue.jpg',
      grey = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/small/tieadvancedv1/textures/tieadvancedv1grey.jpg',
    },
  Fac = {[2]=true},
  arcs = {fixed = { range=3, type = {'front'}}},
  moveSet = {'btl1','bbl1','bbr1','btr1','wtl2','wbl2','bs2','wbr2','wtr2','rtl2t','rtr2t','wtl3','wbl3','bs3','wbr3','wtr3','ws4','rk4','ws5'},
  mesh = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/Small/tieadvancedv1/tieadvv1.obj',
  keywords = {'TIE'}
}

masterShipDB['lambdaclasst4ashuttle']={
  name = 'Lambda Class Shuttle',
  Hull = 6,
  Shield = 4,
  size = 'large',
  agi = 1,
  XWS = 'lambdaclasst4ashuttle',
    newSpawner = true,
    textures = {
      standard = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/large/lambdaclasst4ashuttle/textures/standard.jpg',
    },
  Fac = {[2]=true},
  arcs = {fixed = { range=3, type = {'frontback'}}},
  moveSet = {'bbl1','bs1','bbr1','rtl2','wbl2','bs2','wbr2','rtr2','rbl3','ws3','rbr3','rs0'},
  mesh = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/large/lambdaclasst4ashuttle/lambda.obj'
}

masterShipDB['tiephphantom']={
  name = 'TIE/ph Phantom',
  Hull = 3,
  Shield = 2,
  size = 'small',
  agi = 2,
  XWS = 'tiephphantom',
    newSpawner = true,
    textures = {
      blue = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/small/tiephphantom/textures/tiephphantomblue.jpg',
      grey = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/small/tiephphantom/textures/tiephphantomgrey.jpg',
      sigma = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/small/tiephphantom/textures/tiephphantomsigma.jpg',
      echo = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/small/tiephphantom/textures/tiephphantomwhite.jpg',
    },
  Fac = {[2]=true},
  arcs = {fixed = { range=3, type = {'front'}}},
  moveSet = {'wtl1','wbl1','wbr1','wtr1','wtl2','bbl2','bs2','bbr2','wtr2','wtl3','wbl3','bs3','wbr3','wtr3','rk3','ws4','rk4'},
  mesh = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/Small/tiephphantom/tiephantom.obj',
  keywords = {'TIE'}
}

masterShipDB['vt49decimator']={
  name = 'VT-49 Decimator',
  Hull = 12,
  Shield = 4,
  size = 'large',
  ProximityHider = true,
  agi = 0,
  XWS = 'vt49decimator',
  newSpawner = true,
  textures = {
   grey = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/large/vt49decimator/textures/grey.jpg',
   black = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/large/vt49decimator/textures/black.jpg',
},
  Fac = {[2]=true},
  arcs = {turret = {main = {name = 'primary', type={'doubleturret'}}}},
  moveSet = {'rtl1','bbl1','bs1','bbr1','rtr1','wtl2','wbl2','bs2','wbr2','wtr2','wtl3','wbl3','ws3','wbr3','wtr3','ws4'},
  mesh = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/Large/vt49decimator/vt49decimator.obj'
}

masterShipDB['tieagaggressor']={
  name = 'TIE/ag Aggressor',
  Hull = 4,
  Shield = 1,
  size = 'small',
  agi = 2,
  XWS = 'tieagaggressor',
    newSpawner = true,
    textures = {
      blue = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/Small/tieagaggressor/textures/tieagaggressorblue.jpg', 
      grey = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/Small/tieagaggressor/textures/tieagaggressorgrey.jpg', 
    },
  Fac = {[2]=true},
  arcs = {fixed = { range=3, type = {'front'}}},
  moveSet = {'wbl1','bs1','wbr1','wtl2','bbl2','bs2','bbr2','wtr2','wtl3','wbl3','bs3','wbr3','wtr3','ws4','rk4'},
  mesh = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/Small/tieagaggressor/tieaggressor.obj',
  keywords = {'TIE'}
}

masterShipDB['btls8kwing']={
  name = 'K-Wing',
  Hull = 6,
  Shield = 3,
  size = 'medium',
  agi = 1,
  XWS = 'btls8kwing',
    newSpawner = true,
    textures = {
      standard = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/Medium/btls8kwing/textures/standard.jpg', 
      miranda = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/Medium/btls8kwing/textures/MirandaDoni.jpg', 
      esege= 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/Medium/btls8kwing/textures/EsegeTuketu.jpg', 
    },
  Fac = {[1]=true},
  arcs = {turret = {main = {name = 'primary', type={'doubleturret'}}}},
  moveSet = {'bbl1','bs1','bbr1','wtl2','wbl2','bs2','wbr2','wtr2','wbl3','ws3','wbr3'},
  mesh = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/Medium/btls8kwing/kwing.obj'
}

masterShipDB['arc170starfighter']={
  name = 'ARC-170',
  Hull = 6,
  Shield = 3,
  size = 'medium',
  agi = 1,
  XWS = 'arc170starfighter',
    newSpawner = true,
    textures = {
      rebel = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/Medium/arc170starfighter/textures/rebel.jpg', 
      republic = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/Medium/arc170starfighter/textures/republic.jpg', 
    },
  Fac = {[1]=true,[6]=true},
  arcs = {fixed = { range=3, type = {'frontback'}}},
  moveSet = {'bbl1','bs1','bbr1','wtl2','bbl2','bs2','bbr2','wtr2','rtl3','wbl3','ws3','wbr3','rtr3','rs4','rk4'},
  mesh = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/Medium/arc170starfighter/arc170.obj'
}

masterShipDB['attackshuttle']={
  name = 'Attack Shuttle',
  Hull = 3,
  Shield = 1,
  size = 'small',
  agi = 2,
  XWS = 'attackshuttle',
    newSpawner = true,
    textures = {
      standard = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/Small/attackshuttle/textures/standard.jpg', 
    },
  Fac = {[1]=true},
  arcs = {fixed = { range=3, type = {'front'}}},
  moveSet = {'rtl1','bbl1','bs1','bbr1','rtr1','wtl2','wbl2','bs2','wbr2','wtr2','rtl3','wbl3','ws3','wbr3','rtr3','ws4','rk4'},
  mesh = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/Small/attackshuttle/attackshuttle.obj'
}

masterShipDB['t65xwing']={
  name = 'X-Wing',
  Hull = 4,
  Shield = 2,
  size = 'small',
  agi = 2,
  XWS = 't65xwing',
    newSpawner = true,
    textures = {
      standard = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/Small/t65xwing/textures/standard.png', 
      renegade = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/Small/t65xwing/textures/CavernAngelsZealot.png', 
      biggs = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/Small/t65xwing/textures/BiggsDarklighter.png', , 
      garven = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/Small/t65xwing/textures/GarvenDreis.png',  
      porkins = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/Small/t65xwing/textures/JekPorkins.png', 
      luke = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/Small/t65xwing/textures/LukeSkywalker.png', 
      thane = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/Small/t65xwing/textures/ThaneKyrell.png', 
      wedge = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/Small/t65xwing/textures/WedgeAntilles.png',  
    },
  Fac = {[1]=true},
  arcs = {fixed = { range=3, type = {'front'}}},
  moveSet = {'bbl1', 'bs1', 'bbr1', 'wtl2', 'bbl2', 'bs2', 'bbr2', 'wtr2', 'wtl3', 'wbl3', 'ws3', 'wbr3', 'wtr3', 'ws4', 'rtl3t', 'rtr3t', 'rk4' },
  mesh = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/Small/t65xwing/xwing_base.obj',
  keywords = {'X-Wing'},
  Config = {
    States = {
      [1] = {
          Name = "S-Foils (Open)",
          Model = "https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/Small/t65xwing/xwing_open.obj",
          ZRot = 0,
          Message = " opened their wings.",
      },
      [2] = {
          Name = "S-Foils (Closed)",
          Model = "https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/Small/t65xwing/xwing_closed.obj",
          ZRot = 180,
          Message = " closed their wings.",
      }
    },
    ContextText = "Open/Close S-Foils",
    Token = "http://nnxwing.com/Content/TTS/Config/T65.png"
  }
}

masterShipDB['hwk290lightfreighter']={
  name = 'HWK-290',
  Hull = 3,
  Shield = 2,
  size = 'small',
  agi = 2,
  XWS = 'hwk290lightfreighter',
    newSpawner = true,
    textures = {
      brown = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/small/hwk290lightfreighter/textures/hwkbrown.jpg',
      black = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/small/hwk290lightfreighter/textures/hwkblack.jpg',
      kyber = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/small/hwk290lightfreighter/textures/Kyber.jpg',
},
  Fac = {[1]=true,[3]=true},
  arcs = {turret = {main = {name = 'primary', type={'singleturret'}}}},
  moveSet = {'bbl1','bs1','bbr1','wtl2','wbl2','bs2','wbr2','wtr2','rtl3','wbl3','bs3','wbr3','rtr3','ws4','rs0'},
  mesh = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/Small/hwk290lightfreighter/hwk.obj',
  freighter = {'Freighter'}
}

masterShipDB['rz1awing']={
  name = 'A-Wing',
  Hull = 2,
  Shield = 2,
  size = 'small',
  agi = 3,
  XWS = 'rz1awing',
    newSpawner = true,
    textures = {
      arvel = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/Small/rz1awing/textures/ArvelCrynyd.png', 
      shara = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/Small/rz1awing/textures/SharaBey.png', 
      green = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/Small/rz1awing/textures/GreenSquadronPilot.png', 
      jake = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/Small/rz1awing/textures/JakeFarrell.png', 
      sabine = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/Small/rz1awing/textures/SabineWren.png', 
      wedge = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/Small/rz1awing/textures/WedgeAntilles.png', 
      hera= 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/Small/rz1awing/textures/HeraSyndulla.png', 
      blank = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/Small/rz1awing/textures/blank.png', 
    },
  Fac = {[1]=true},
  arcs = {fixed = { range=3, type = {'front'}}},
  moveSet = {'wtl1','wtr1','btl2','bbl2','bs2','bbr2','btr2','rbl3s','wtl3','wbl3','bs3','wbr3','wtr3','rbr3s','bs4','bs5','rk5'},
  mesh = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/Small/rz1awing/awing.obj',
  keywords = {'A-Wing'}
}

masterShipDB['fangfighter']={
  name = 'Fang Fighter',
  newSpawner = true,
  textures = {
    blank = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/small/fangfighter/textures/Blank.jpg',
    bodica = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/small/fangfighter/textures/Bodica.jpg',
    dirk = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/small/fangfighter/textures/Dirk.jpg',
    new = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/small/fangfighter/textures/New.jpg',
    original = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/small/fangfighter/textures/Original.jpg',
    rebelfenn = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/small/fangfighter/textures/Rebel-Fenn.jpg',
    volunteer = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/small/fangfighter/textures/Volunteer.jpg',
    red = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/small/fangfighter/textures/red.jpg',
    sabine = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/small/fangfighter/textures/Sabine-Fang.jpg',
  },
  Hull = 4,
  Shield = 0,
  size = 'small',
  agi = 3,
  XWS = 'fangfighter',
  Fac = {[3]=true},
  arcs = {fixed = { range=3, type = {'front'}}},
  moveSet = {'wtl1','wtr1','rtl2t','btl2','bbl2','bs2','bbr2','btr2','rtr2t','wtl3','wbl3','bs3','wbr3','wtr3','ws4','rk4','ws5'},
  --mesh = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/Small/SCU_fangfighter/fangfighter.obj'
  mesh = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/small/fangfighter/ship-base.obj'
}

masterShipDB['z95af4headhunter']={
  name = 'Z-95 Headhunter',
  Hull = 2,
  Shield = 2,
  size = 'small',
  agi = 2,
  XWS = 'z95af4headhunter',
    newSpawner = true,
    textures = {
      bandit = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/Small/z95af4headhunter/textures/BanditSquadronPilot.png', 
      tala = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/Small/z95af4headhunter/textures/TalaSquadronPilot.png', 
      pirate = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/Small/z95af4headhunter/textures/BinayrePirate.png', 
      blacksun = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/Small/z95af4headhunter/textures/BlackSunSoldier.png', 
      blount = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/Small/z95af4headhunter/textures/LieutenantBlount.png', 
      nashtah = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/Small/z95af4headhunter/textures/NashtahPup.png', 
      bossk = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/Small/z95af4headhunter/textures/Bossk.png', 
      ndru = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/Small/z95af4headhunter/textures/NdruSuhlak.png', 
      airen = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/Small/z95af4headhunter/textures/AirenCracken.png', 
    },
  Fac = {[1]=true,[3]=true},
  arcs = {fixed = { range=3, type = {'front'}}},
  moveSet = {'wbl1','bs1','wbr1','wtl2','bbl2','bs2','bbr2','wtr2','wtl3','wbl3','bs3','wbr3','wtr3','rk3','ws4','rk4'},
  mesh = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/Small/z95af4headhunter/z95.obj'
}

masterShipDB['m12lkimogilafighter']={
  name = 'M12-L Kimogila',
  Hull = 7,
  Shield = 2,
  size = 'medium',
  agi = 2,
  XWS = 'm12lkimogilafighter',
    newSpawner = true,
    textures = {
      cartel = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/Medium/m12lkimogilafighter/textures/CartelExecutioner.png', 
      dalan = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/Medium/m12lkimogilafighter/textures/DalanOberos.png', 
      torani = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/Medium/m12lkimogilafighter/textures/ToraniKulda.png', 
    },
  Fac = {[3]=true},
  arcs = {fixed = { range=3, type = {'front'}}},
  moveSet = {'rtl1','wbl1','bs1','wbr1','rtr1','wtl2','bbl2','bs2','bbr2','wtr2','wtl3','wbl3','bs3','wbr3','wtr3','rk4'},
  mesh = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/Medium/m12lkimogilafighter/kimogila.obj'
}

masterShipDB['ewing']={
  name = 'E-Wing',
  Hull = 3,
  Shield = 3,
  size = 'small',
  agi = 3,
  XWS = 'ewing',
    newSpawner = true,
    textures = {
      rogue = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/small/ewing/textures/RogueSquadronEscort.jpg',
      knave = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/small/ewing/textures/KnaveSquadronEscort.jpg',
      gavin = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/small/ewing/textures/GavinDarklighter.jpg',
      corran = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/small/ewing/textures/CorranHorn.jpg',
    },
  Fac = {[1]=true},
  arcs = {fixed = { range=3, type = {'front'}}},
  moveSet = {'rtl1','bbl1','bs1','bbr1','rtr1','wtl2','wbl2','bs2','wbr2','wtr2','rbl3s','wtl3','wbl3','bs3','wbr3','wtr3','rbr3s','bs4','rk4','ws5'},
  mesh = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/Small/ewing/ewing.obj'
}

masterShipDB['tieininterceptor']={
  name = 'TIE/in Interceptor',
  Hull = 3,
  Shield = 0,
  size = 'small',
  agi = 3,
  XWS = 'tieininterceptor',
    newSpawner = true,
    textures = {
      blue = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/small/tieininterceptor/textures/tieinterceptorblue.jpg',
      grey = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/small/tieininterceptor/textures/tieinterceptorgrey.jpg',
      red = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/small/tieininterceptor/textures/tieinterceptorred.jpg',
      skystrike = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/small/tieininterceptor/textures/tieinterceptorss.jpg',
      181 = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/small/tieininterceptor/textures/tieinterceptor181.jpg',
    },
  Fac = {[2]=true},
  arcs = {fixed = { range=3, type = {'front'}}},
  moveSet = {'wtl1','wtr1','btl2','bbl2','bs2','bbr2','btr2','rbl3s','wtl3','wbl3','bs3','wbr3','wtr3','rbr3s','bs4','rk4','ws5'},
  mesh = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/Small/tieininterceptor/tieinterceptor.obj',
  keywords = {'TIE'}
}

masterShipDB['lancerclasspursuitcraft']={
  name = 'Lancer Pursuit Craft',
  Hull = 8,
  Shield = 2,
  size = 'large',
  ProximityHider = true,
  agi = 2,
  XWS = 'lancerclasspursuitcraft',
    newSpawner = true,
    textures = {
      standard = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/Large/lancerclasspursuitcraft/textures/standard.jpg', 
    },
  Fac = {[3]=true},
  arcs = {fixed = { range=3, type = {'front'}}, turret = {main = {name = 'primary', type={'singleturret'}}}},
  moveSet = {'wbl1','ws1','wbr1','wtl2','wbl2','bs2','wbr2','wtr2','btl3','bbl3','bs3','bbr3','btr3','bs4','ws5','rk5'},
  mesh = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/Large/lancerclasspursuitcraft/lancer.obj',
}

masterShipDB['tierereaper']={
  name = 'TIE/re Reaper',
  Hull = 6,
  Shield = 2,
  size = 'medium',
  agi = 1,
  XWS = 'tierereaper',
    newSpawner = true,
    textures = {
      blue = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/medium/tiereaper/textures/tierereaperblue.jpg', 
      grey = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/medium/tiereaper/textures/tierereapergrey.jpg', 
    },
  Fac = {[2]=true},
  arcs = {fixed = { range=3, type = {'front'}}},
  moveSet = {'rbl1s','rtl1','bbl1','bs1','bbr1','rtr1','rbr1s','rtl2','wbl2','bs2','wbr2','rtr2','wbl3','bs3','wbr3','rs0'},
  mesh = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/Medium/tiereaper/tiereaper.obj',
  keywords = {'TIE'}
}

masterShipDB['m3ainterceptor']={
  name = 'M3-A Interceptor',
  Hull = 3,
  Shield = 1,
  size = 'small',
  agi = 3,
  XWS = 'm3ainterceptor',
    newSpawner = true,
    textures = {
      cartel = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/Small/m3ainterceptor/textures/CartelSpacer.jpg', 
      tansarii = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/Small/m3ainterceptor/textures/TansariiPointVeteran.jpg', 
      gargor = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/Small/m3ainterceptor/textures/G4rG0r.jpg', 
      sunny = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/Small/m3ainterceptor/textures/SunnyBounder.jpg', 
      genesis = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/Small/m3ainterceptor/textures/GenesisRed.jpg', 
    },
  Fac = {[3]=true},
  arcs = {fixed = { range=3, type = {'front'}}},
  moveSet = {'wtl1','bbl1','bbr1','wtr1','wtl2','wbl2','bs2','wbr2','wtr2','wbl3','bs3','wbr3','rk3','ws4','ws5','rk5'},
  mesh = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/Small/m3ainterceptor/m3a.obj'
}

masterShipDB['jumpmaster5000']={
  name = 'JumpMaster 5000',
  Hull = 6,
  Shield = 3,
  size = 'large',
  agi = 1,
  XWS = 'jumpmaster5000',
    newSpawner = true,
    textures = {
      standard = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/Large/jumpmaster5000/textures/standard.png', 
      nom = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/Large/jumpmaster5000/textures/NomLumb.png', 
    },
  Fac = {[3]=true},
  arcs = {turret = {main = {name = 'primary', type={'singleturret'}}}},
  moveSet = {'wtl1','bbl1','bs1','wbr1','rtr1','wtl2','bbl2','bs2','wbr2','rtr2','rbl3s','bbl3','bs3','wbr3','ws4','rk4'},
  mesh = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/Large/jumpmaster5000/jumpmaster.obj'
}

masterShipDB['customizedyt1300lightfreighter']={
  name = 'Customized YT-1300',
  Hull = 8,
  Shield = 3,
  size = 'large',
  ProximityHider = true,
  agi = 1,
  XWS = 'customizedyt1300lightfreighter',
    newSpawner = true,
    textures = {
      standard = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/Large/customizedyt1300lightfreighter/textures/standard.jpg', 
    },
  Fac = {[3]=true},
  arcs = {turret = {main = {name = 'primary', type={'doubleturret'}}}},
  Docking = true,
  moveSet = {'bbl1','bs1','bbr1','wtl2','wbl2','bs2','wbr2','wtr2','wtl3','wbl3','bs3','wbr3','wtr3','rbl3s','rbr3s','ws4','rk4'},
  mesh = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/Large/customizedyt1300lightfreighter/yt1300.obj',
  keywords = {'Freighter', 'YT-1300'}
}

masterShipDB['escapecraft']={
  name = 'Escape Craft',
  Hull = 2,
  Shield = 2,
  size = 'small',
  agi = 2,
  XWS = 'escapecraft',
    newSpawner = true,
    textures = {
      standard = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/Small/escapecraft/textures/standard.png', 
    },
  Fac = {[3]=true},
  arcs = {fixed = { range=3, type = {'front'}}},
  moveSet = {'bbl1','bs1','bbr1','rtl2','wbl2','bs2','wbr2','rtr2','wbl3','ws3','wbr3','rk3','rs0'},
  mesh = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/Small/escapecraft/escapecraft.obj'
}

masterShipDB['tiefofighter']={
	name = 'TIE/fo FO',
	Hull = 3,
	Shield = 1,
	size = 'small',
	agi = 3,
	XWS = 'tiefofighter',
    newSpawner = true,
    textures = {
      standard = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/Small/tiefofighter/textures/standard.png', 
    },
	Fac = {[5]=true},
	arcs = {fixed = { range=3, type = {'front'}}},
	moveSet = {'wtl1','wtr1','rbl2s','btl2','bbl2','bs2','bbr2','btr2','rbr2s','wtl3','wbl3','bs3','wbr3','wtr3','ws4','rk4','ws5'},
	mesh = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/Small/tiefofighter/Tie_FO.obj',
  keywords = {'TIE'}
}

masterShipDB['tiesffighter']={
	name = 'TIE/sf SF',
	Hull = 3,
	Shield = 3,
	size = 'small',
	agi = 2,
	XWS = 'tiesffighter',
    newSpawner = true,
    textures = {
      standard = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/Small/tiesffighter/textures/standard.png', 
    },
	Fac = {[5]=true},
  arcs = {fixed = { range=3, type = {'front'}}, turret = {main = {name = 'primary', type= {'front', 'back'}}}},
	moveSet = {'rtl1','bbl1','bs1','bbr1','rtr1','wtl2','bbl2','bs2','bbr2','wtr2','rbl3s','wtl3','wbl3','bs3','wbr3','wtr3','rbr3s','ws4','ws5'},
	mesh = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/Small/tiesffighter/Tie_SF.obj',
  keywords = {'TIE'}
}

masterShipDB['upsilonclasscommandshuttle']={
	name = 'Upsilon Class Shuttle',
	Hull = 6,
	Shield = 6,
	size = 'large',
  ProximityHider = true,
	agi = 1,
	XWS = 'upsilonclasscommandshuttle',
    newSpawner = true,
    textures = {
      standard = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/Large/upsilonclasscommandshuttle/textures/standard.jpg', 
    },
	Fac = {[5]=true},
	arcs = {fixed = { range=3, type = {'front'}}},
	moveSet = {'rtl1','wbl1','bs1','wbr1','rtr1','wtl2','bbl2','bs2','bbr2','wtr2','rtl3','wbl3','ws3','wbr3','rtr3','rs0'},
	mesh = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/Large/upsilonclasscommandshuttle/Upsilon_Shuttle.obj'
}
masterShipDB['tievnsilencer']={
	name = 'TIE Silencer',
	Hull = 4,
	Shield = 2,
	size = 'small',
	agi = 3,
	XWS = 'tievnsilencer',
    newSpawner = true,
    textures = {
      standard = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/Small/tievnsilencer/textures/standard.png', 
    },
	Fac = {[5]=true},
	arcs = {fixed = { range=3, type = {'front'}}},
	moveSet={'wtl1','wtr1','btl2','bbl2','bs2','bbr2','btr2','rtl3t','wtl3','wbl3','bs3','wbr3','wtr3','rtr3t','bs4','rk4','bs5'},
	mesh = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/Small/tievnsilencer/Tie_VN.obj',
  keywords = {'TIE'}
}

masterShipDB['t70xwing']={
    name = 'T-70 X-Wing',
    Hull = 4,
    Shield = 3,
    size = 'small',
    agi = 2,
    XWS = 't70xwing',
    newSpawner = true,
    textures = {
      standard = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/Small/t70xwing/textures/RedSquadronExpert.png', 
      snap = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/Small/t70xwing/textures/SnapHoH.png', 
      commanderpoe= 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/Small/t70xwing/textures/PoeHoH.png', 
      blackone = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/Small/t70xwing/textures/PoeDameron.png', 
    },
    Fac = {[4]=true},
    arcs = {fixed = { range=3, type = {'front'}}},
    moveSet={'bbl1','bs1','bbr1','wtl2','bbl2','bs2','bbr2','wtr2','rtl3t','wtl3','wbl3','bs3','wbr3','wtr3','rtr3t','ws4','rk4'},
    keywords = {'X-Wing'},
    mesh = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/Small/t70xwing/t70_base.obj',
    Config = {
      States = {
        [1] = {
            Name = "S-Foils (Open)",
            Model = "https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/Small/t70xwing/t70_open.obj",
            ZRot = 0,
            Message = " opened their wings.",
        },
        [2] = {
            Name = "S-Foils (Closed)",
            Model = "https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/Small/t70xwing/t70_closed.obj",
            ZRot = 180,
            Message = " closed their wings.",
        }
      },
      ContextText = "Open/Close S-Foils",
      Token = "http://nnxwing.com/Content/TTS/Config/T70.png"
    }
  }

masterShipDB['rz2awing']={
    name = 'A-Wing RZ-2',
    XWS = 'rz2awing',
    Hull = 2,
    Shield = 2,
    size = 'small',
    agi = 3,
    newSpawner = true,
    textures = {
      green = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/Small/rz2awing/textures/green.png', 
      red = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/Small/rz2awing/textures/red.png',
      orange = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/Small/rz2awing/textures/orange.png', 
      blue = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/Small/rz2awing/textures/blue.png', 
    },
    Fac = {[4]=true},
    arcs = {turret = {main = {name = 'primary', type= {'front', 'back'}}}},
    mesh = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/Small/rz2awing/res_awing.obj',
    moveSet = {'wtl1','wtr1','btl2','bbl2','bs2','bbr2','btr2','rbl3s','wtl3','bbl3','bs3','bbr3','wtr3','rbr3s','bs4','bs5','rk5'},
    keywords = {'A-Wing'}
  }

masterShipDB['mg100starfortress']={
  name = 'MG-100 StarFortress',
  Hull = 9,
  Shield = 3,
  size = 'large',
  agi = 1,
  XWS = 'mg100starfortress',
    newSpawner = true,
    textures = {
      standard = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/Large/mg100starfortress/textures/standard.jpg', 
      vennie = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/Large/mg100starfortress/textures/Vennie.jpg', 
      paige = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/Large/mg100starfortress/textures/PaigeTico.jpg', 
    },
  Fac = {[4]=true},
  arcs = {fixed = { range=3, type = {'front'}}, turret = {main = {name = 'primary', type={'doubleturret'}}}},
  moveSet = {'rs0','rtl1','bbl1','bs1','bbr1','rtr1','wtl2','wbl2','bs2','wbr2','wtr2','rbl3','ws3','rbr3'},
  mesh = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/Large/mg100starfortress/starfortress.obj'
}

masterShipDB['modifiedtielnfighter']={
  name = 'Modified TIE/ln Fighter',
  Hull = 3,
  Shield = 0,
  size = 'small',
  agi = 3,
  XWS = 'modifiedtielnfighter',
    newSpawner = true,
    textures = {
      standard = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/Small/modifiedtielnfighter/textures/standard.png', 
    },
  Fac = {[3]=true},
  arcs = {fixed = { range=3, type = {'front'}}},
  moveSet = {'wtl1','wtr1','wtl2','bbl2','bs2','bbr2','wtr2','wtl3','wbl3','bs3','wbr3','wtr3','rk3','ws4','rs5'},
  mesh = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/Small/modifiedtielnfighter/miningguildtie.obj',
  keywords = {'TIE'}
}

masterShipDB['scavengedyt1300lightfreighter']={
  name = 'Scavenged YT-1300',
  Hull = 8,
  Shield = 3,
  size = 'large',
  ProximityHider = true,
  agi = 1,
  XWS = 'scavengedyt1300lightfreighter',
    newSpawner = true,
    textures = {
      standard = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/Large/scavengedyt1300lightfreighter/textures/standard.jpg', 
    },
  Fac = {[4]=true},
  arcs = {turret = {main = {name = 'primary', type={'doubleturret'}}}},
  moveSet = {'wbl1','bs1','wbr1','wtl2','bbl2','bs2','bbr2','wtr2','wtl3','wbl3','ws3','wbr3','wtr3','rbl3s','rbr3s','rs4'},
  mesh = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/Large/scavengedyt1300lightfreighter/scavengedyt1300.obj',
  keywords = {'Freighter', 'YT-1300'}
}

--w3ship
masterShipDB['delta7aethersprite']={
	name = 'Delta-7',
	Hull = 3,
	Shield = 1,
	size = 'small',
	agi = 3,
	XWS = 'delta7aethersprite',
    newSpawner = true,
    textures = {
      ahsoka = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/Small/delta7aethersprite/textures/AhsokaTano.png', 
      anakin = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/Small/delta7aethersprite/textures/AnakinSkywalker.png', 
      barriss = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/Small/delta7aethersprite/textures/BarrissOffee.png', 
      knight = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/Small/delta7aethersprite/textures/JediKnight.png', 
      lumi = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/Small/delta7aethersprite/textures/LuminaraUnduli.png', 
      mace = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/Small/delta7aethersprite/textures/MaceWindu.png', 
      obi = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/Small/delta7aethersprite/textures/Obi-WanKenobi.png', 
      plo = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/Small/delta7aethersprite/textures/PloKoon.png', 
      saesee= 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/Small/delta7aethersprite/textures/SaeseeTiin.png', 
    },
	Fac = {[6]=true},
	arcs = {fixed = { range=3, type = {'front'}}},
	moveSet={'wtl1','bbl1','bbr1','wtr1','rbl2s','wtl2','bbl2','bs2','bbr2','wtr2','rbr2s','wbl3','bs3','wbr3','ws4','rk4','ws5','rk5'},
	mesh = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/Small/delta7aethersprite/Jedi_Delta7.obj',
  Config = {
    States = {
      [1] = {
          Name = "Normal",
          Model = nil,
          ZRot = 0,
          Message = " removed hyperspace ring,",
      },
      [2] = {
          Name = "Hyperspace ring mounted",
          Model = "https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships/Small/GRP_Hyperspace_Ring/hyperspace_ring_attachment.obj",
          ZRot = 180,
          Message = " mounted an hyperspace ring.",
      }
    },
    ContextText = "Mount/unmount hyperspace ring",
  }
}

masterShipDB['delta7baethersprite']={
	name = 'Delta-7B',
	Hull = 3,
	Shield = 3,
	size = 'small',
	agi = 2,
	XWS = 'delta7baethersprite ',
    newSpawner = true,
    textures = {
      ahsoka = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/Small/delta7aethersprite/textures/AhsokaTano.png', 
      anakin = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/Small/delta7aethersprite/textures/AnakinSkywalker.png', 
      barriss = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/Small/delta7aethersprite/textures/BarrissOffee.png', 
      knight = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/Small/delta7aethersprite/textures/JediKnight.png', 
      lumi = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/Small/delta7aethersprite/textures/LuminaraUnduli.png', 
      mace = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/Small/delta7aethersprite/textures/MaceWindu.png', 
      obi = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/Small/delta7aethersprite/textures/Obi-WanKenobi.png', 
      plo = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/Small/delta7aethersprite/textures/PloKoon.png', 
      saesee= 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/Small/delta7aethersprite/textures/SaeseeTiin.png', 
    },
	Fac = {[6]=true},
	arcs = {fixed = { range=3, type = {'front'}}},
	moveSet={'wtl1','bbl1','bbr1','wtr1','rbl2s','wtl2','bbl2','bs2','bbr2','wtr2','rbr2s','wbl3','bs3','wbr3','ws4','rk4','ws5','rk5'},
	mesh = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/Small/delta7aethersprite/Jedi_Delta7.obj',
  Config = {
    States = {
      [1] = {
          Name = "Normal",
          Model = nil,
          ZRot = 0,
          Message = " removed hyperspace ring,",
      },
      [2] = {
          Name = "Hyperspace ring mounted",
          Model = "https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships/Small/GRP_Hyperspace_Ring/hyperspace_ring_attachment.obj",
          ZRot = 180,
          Message = " mounted an hyperspace ring.",
      }
    },
    ContextText = "Mount/unmount hyperspace ring",
  }
}

masterShipDB['v19torrentstarfighter']={
	name = 'V-19',
	Hull = 5,
	Shield = 0,
	size = 'small',
	agi = 2,
	XWS = 'v19torrentstarfighter',
    newSpawner = true,
    textures = {
      standard = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/Small/v19torrentstarfighter/textures/standard.png', 
    },
	Fac = {[6]=true},
	arcs = {fixed = { range=3, type = {'front'}}},
	moveSet ={'rtl1','bbl1','bs1','bbr1','rtr1','rtl2t','wtl2','wbl2','bs2','wbr2','wtr2','rtr2t','rbl3','bs3','rbr3','rk3','ws4'},
	mesh = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/Small/v19torrentstarfighter/V-19_Torrent.obj'
}


masterShipDB['vultureclassdroidfighter']={
  name = 'Vulture-Class Droid',
  Hull = 3,
  Shield = 0,
  size = 'small',
  agi = 2,
  XWS = 'vultureclassdroidfighter',
    newSpawner = true,
    textures = {
      drone = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/Small/vultureclassdroidfighter/textures/SeperatistDrone.png',
      hunter = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/Small/vultureclassdroidfighter/textures/PreciseHunter.png',
      proto = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/Small/vultureclassdroidfighter/textures/HaorChallPrototype.png',
      311 = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/Small/vultureclassdroidfighter/textures/DFS-311.png',
      081 = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/Small/vultureclassdroidfighter/textures/DFS-081.png', 
    },
  Fac = {[7]=true},
  arcs = {fixed = { range=3, type = {'front'}}},
  moveSet = {'wtl1','wtr1','rk1','rtl2t','btl2','wbl2','bs2','wbr2','btr2','rtr2t','wtl3','rbl3','bs3','rbr3','wtr3','bs4','ws5'},
  keywords = {'Droid'},
  mesh = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/Small/vultureclassdroidfighter/Vulture.obj',
  Config = {
    States = {
      [1] = {
          Name = "Struts (Closed)",
          Model = "https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/Small/vultureclassdroidfighter/Vulture_Closed.obj",
          ZRot = 0,
          Message = " closed their struts.",
      },
      [2] = {
          Name = "Struts (Open)",
          Model = "https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/Small/vultureclassdroidfighter/Vulture_Open.obj",
          ZRot = 180,
          Message = " opened their struts.",
      }
    },
    ContextText = "Open/Close Struts",
    Token = "http://nnxwing.com/Content/TTS/Config/VultureDroid.png?1.0.1"
  }
}
masterShipDB['belbulab22starfighter']={
  name = 'Belbullab-22',
  Hull = 4,
  Shield = 2,
  size = 'small',
  agi = 2,
  XWS = 'belbulab22starfighter',
    newSpawner = true,
    textures = {
      standard = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/Small/belbulab22starfighter/textures/standard.png', 
      wat= 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/Small/belbulab22starfighter/textures/WatTambor.png', 
    },
  Fac = {[7]=true},
  arcs = {fixed = { range=3, type = {'front'}}},
  moveSet = {'wtl1','wbl1','wbr1','wtr1','wtl2','bbl2','bs2','bbr2','wtr2','rbl3s','rtl3','wbl3','bs3','wbr3','rtr3','rbr3s','ws4','ws5'},
  mesh = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/Small/belbulab22starfighter/Belbullab.obj'
}

masterShipDB['sithinfiltrator']={
  name = 'Sith Infiltrator',
  Hull = 6,
  Shield = 4,
  size = 'large',
  agi = 1,
  XWS = 'sithinfiltrator',
    newSpawner = true,
    textures = {
      standard = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/Large/sithinfiltrator/textures/standard.png',
      maul = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/Large/sithinfiltrator/textures/DarthMaul.png',  
    },
  Fac = {[7]=true},
  arcs = {fixed = { range=3, type = {'front'}}},
  moveSet = {'rtl1','bbl1','bs1','bbr1','rtr1','rbl2s','wtl2','bbl2','bs2','bbr2','wtr2','rbr2s','wtl3','wbl3','bs3','wbr3','wtr3','ws4','rk5'},
  mesh = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/Large/sithinfiltrator/Infiltrator.obj'
}

masterShipDB['resistancetransport']={
    name = 'Resistance Transport',
    XWS = 'resistancetransport',
    Hull = 5,
    Shield = 3,
    size = 'small',
    agi = 1,
    newSpawner = true,
    textures = {
      standard = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/Small/resistancetransport/textures/standard.png', 
    },
    Fac = {[4]=true},
    arcs = {fixed = { range=3, type = {'front'}}},
    mesh = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/Small/resistancetransport/transport.obj',
    moveSet = {'rbl1r','rbr1r','rs0','rbl1r','rbr1r','rtl1','bbl1','bs1','bbr1','rtr1','wtl2','wbl2','bs2','wbr2','wtr2','rbl3','ws3','rbr3','rs4'}
}

masterShipDB['resistancetransportpod']={
    name = 'Resistance Transport Pod',
    XWS = 'resistancetransportpod',
    Shield = 1,
    Hull = 3,
    size = 'small',
    agi = 2,
    newSpawner = true,
    textures = {
      standard = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/Small/resistancetransportpod/textures/standard.png', 
    },
    Fac = {[4]=true},
    arcs = {fixed = { range=3, type = {'front'}}},
    mesh = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/Small/resistancetransportpod/transport_pod.obj',
    moveSet = {'rtl1','bbl1','bs1','bbr1','rtr1','wtl2','wbl2','bs2','wbr2','wtr2','rbl3','ws3','rbr3','rk3','rs4'}
}

masterShipDB['hyenaclassdroidbomber']={
  name = 'Hyena-Class Droid Bomber',
  Hull = 5,
  Shield = 0,
  size = 'small',
  agi = 2,
  XWS = 'hyenaclassdroidbomber',
    newSpawner = true,
    textures = {
      standard = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/Small/hyenaclassdroidbomber/textures/standard.png', 
    },
  Fac = {[7]=true},
  arcs = {fixed = { range=3, type = {'front'}}},
  moveSet = {'wtl1','rbl1','ws1','rbr1','wtr1','btl2','wbl2','bs2','wbr2','btr2','rk2','rtl2t','rtr2t','wtl3','bs3','wtr3','ws4','rs5'},
  keywords = {'Droid'},
  mesh = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/Small/CIS_Hyena/Hyena_Base.obj',
  Config = {
    States = {
      [1] = {
          Name = "Struts (Closed)",
          Model = "https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/Small/hyenaclassdroidbomber/Hyena_Closed.obj",
          ZRot = 0,
          Message = " closed their struts.",
      },
      [2] = {
          Name = "Struts (Open)",
          Model = "https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/Small/hyenaclassdroidbomber/Hyena_Open.obj",
          ZRot = 180,
          Message = " opened their struts.",
      }
    },
    ContextText = "Open/Close Struts",
    Token = "http://nnxwing.com/Content/TTS/Config/HyenaDroid.png?1.0.1",

  }
}

masterShipDB['nabooroyaln1starfighter']={
	name ='N-1 StarFighter',
	Hull = 3,
	Shield = 2,
	size = 'small',
	agi = 2,
	XWS = 'nabooroyaln1starfighter',
    newSpawner = true,
    textures = {
      yellow = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/Small/nabooroyaln1starfighter/textures/yellow.png',
      silver = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/Small/nabooroyaln1starfighter/textures/silver.png', 
    },
	Fac = {[6]=true},
	arcs = {fixed = { range=3, type = {'front'}}},
	moveSet = {'wbl1','ws1','wbr1','wtl2','bbl2','bs2','bbr2','wtr2','wtl3','bbl3','bs3','bbr3','wtr3','rtl3t','rtr3t','ws4','ws5'},
	mesh = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/Small/nabooroyaln1starfighter/Naboo_Royal_N1.obj'
}

masterShipDB['nantexclassstarfighter']={
  name = 'Nantex-Class StarFighter',
  Hull = 4,
  Shield = 0,
  size = 'small',
  agi = 3,
  XWS = 'nantexclassstarfighter',
    newSpawner = true,
    textures = {
      standard = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/Small/nantexclassstarfighter/textures/standard.png', 
    },
  Fac = {[7]=true},
  arcs = {fixed = { range=3, type = {'bullseye'}}, turret={main={name= 'primary', type={'left', 'front', 'right'}}}},
  moveSet = {'wtl1','bbl1','bbr1','wtr1','wtl2','bbl2','bs2','bbr2','wtr2','wtl3','bbl3','bs3','bbr3','wtr3','rbl3s','rbr3s','ws4','ws5','rk5'},
  mesh = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/Small/nantexclassstarfighter/Nantex.obj'
}

masterShipDB['btlbywing']={
	name = 'BTL-B Y-Wing',
	Hull = 5,
	Shield = 3,
	size = 'small',
	agi = 1,
	XWS = 'btlbywing',
    newSpawner = true,
    textures = {
      standard = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/Small/btlbywing/textures/standard.png', 
    },
	Fac = {[6]=true},
	arcs = {fixed = { range=3, type = {'front'}}},
	moveSet = {'wbl1','bs1','wbr1','wtl2','wbl2','bs2','wbr2','wtr2','rtl3','wbl3','ws3','wbr3','rtr3','rs4','rk4'},
  mesh = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/Small/btlbywing/BTLB_YWING.obj',
  keywords = {'Y-Wing'}
}

masterShipDB['fireball']={
  name = 'FireBall',
  Hull = 6,
  Shield = 0,
  size = 'small',
  agi = 2,
  XWS = 'fireball',
    newSpawner = true,
    textures = {
      standard = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/Small/fireball/textures/standard.jpg', 
    },
  Fac = {[4]=true},
  arcs = {fixed = { range=3, type = {'front'}}},
  moveSet = {'wtl1','bbl1','bs1','bbr1','wtr1','wtl2','wbl2','bs2','wbr2','wtr2','rtl3','wbl3','ws3','wbr3','rtr3','rtl3t','rtr3t','rs4'},
  mesh = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/Small/fireball/fireball.obj'
}


masterShipDB['tiebainterceptor']={
    name = 'TIE/ba Interceptor',
    Hull = 2,
    Shield = 2,
    size = 'small',
    agi = 3,
    XWS = 'tiebainterceptor',
    newSpawner = true,
    textures = {
      standard = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/Small/tiebainterceptor/textures/standard.png', 
    },
    Fac = {[5]=true},
    arcs = {fixed = { range=3, type = {'front'}}},
    mesh = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/Small/tiebainterceptor/TieBa.obj',
    moveSet = {'btl1','bbl1','bbr1','btr1','wtl2','bbl2','bs2','bbr2','wtr2','wtl3','wbl3','bs3','wbr3','wtr3','rbl2s','rbr2s','bs4','ws5','rk5'},
    keywords = {'TIE'}
}

masterShipDB['nimbusclassvwing']={
    name = 'Nimbus-class V-wing',
    Hull = 2,
    Shield = 2,
    size = 'small',
    agi = 3,
    XWS = 'nimbusclassvwing',
    newSpawner = true,
    textures = {
      red = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/Small/nimbusclassvwing/textures/VwingRed.png', 
      blue = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/Small/nimbusclassvwing/textures/VwingBlue.png', 
    },
    Fac = {[6]=true},
    arcs = {fixed = { range=3, type = {'front'}}},
    mesh = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/Small/nimbusclassvwing/Republic_V-Wing.obj',
    moveSet = {'wtl1','rbl1','rbr1','wtr1','btl2','bbl2','bs2','bbr2','btr2','rk2','wtl3','wbl3','bs3','wbr3','wtr3','ws4','rk4','ws5'},
    keywords = {'TIE'},
    Config = {
      States = {
        [1] = {
            Name = "Normal",
            Model = nil,
            ZRot = 0,
            Message = " removed hyperspace ring,",
        },
        [2] = {
            Name = "Hyperspace ring mounted",
            Model = "https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships/Small/GRP_Hyperspace_Ring/hyperspace_ring_attachment.obj",
            ZRot = 180,
            Message = " mounted an hyperspace ring.",
        }
      },
      ContextText = "Mount/unmount hyperspace ring",
    }

}

masterShipDB['tierbheavy']={
    name = 'TIE/rb Heavy',
    Hull = 8,
    Shield = 0,
    size = 'medium',
    agi = 1,
    XWS = 'tierbheavy',
    newSpawner = true,
    textures = {
      blue = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/medium/tierbheavy/textures/tierbheavyblue.jpg', 
      grey = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/medium/tierbheavy/textures/tierbheavygrey.jpg', 
    },
    Fac = {[2]=true},
    arcs = {turret = {main={ name = 'primary', type= {'front', 'back'}}}},
    mesh = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/Medium/tierbheavy/tieheavy.obj',
    moveSet = {'rtl1','wbl1','bs1','wbr1','rtr1','wtl2','bbl2','bs2','bbr2','wtr2','rtl3t','rtl3','wbl3','ws3','wbr3','rtr3','rtr3t','ws4'},
    keywords = {'TIE'}
}

masterShipDB['xiclasslightshuttle']={
    name = 'Xi-class Light Shuttle',
    Hull = 5,
    Shield = 2,
    size = 'medium',
    agi = 2,
    XWS = 'xiclasslightshuttle',
    newSpawner = true,
    textures = {
      light = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/Medium/xiclasslightshuttle/textures/Light.jpg', 
      dark = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/Medium/xiclasslightshuttle/textures/Dark.jpg', 
    },
    Fac = {[5]=true},
    arcs = {fixed = { range=3, type = {'front'}}},
    mesh = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/Medium/xiclasslightshuttle/XiClassLightShuttle.obj',
    moveSet = {'rs0','bbl1','bs1','bbr1','wtl2','bbl2','bs2','bbr2','wtr2','rtl3','wbl3','ws3','wbr3','rtr3','ws4'}
}

masterShipDB['laatigunship']={
    name = 'LAAT/i Gunship',
    Hull = 8,
    Shield = 2,
    Charge = 2,
    size = 'medium',
    agi = 1,
    XWS = 'laatigunship',
    newSpawner = true,
    textures = {
      standard = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/Medium/laatigunship/textures/standard.png', 
      hawk = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/Medium/laatigunship/textures/Hawk.png', 
      hound = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/Medium/laatigunship/textures/Hound.png', 
      warthog = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/Medium/laatigunship/textures/Warthog.png', 
    },
    Fac = {[6]=true},
    arcs = {turret = {main = {name = 'primary', type={'doubleturret'}}}},
    mesh = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/Medium/laatigunship/GRP_LAAT.obj',
    moveSet = {'rs0','wbl1','bs1','wbr1','wtl2','wbl2','bs2','wbr2','wtr2','rtl3','wbl3','ws3','wbr3','rtr3','rs4'}
}

masterShipDB['hmpdroidgunship']={
    name = 'HMP Droid Gunship',
    Hull = 5,
    Shield = 3,
    size = 'small',
    agi = 1,
    XWS = 'hmpdroidgunship',
    newSpawner = true,
    textures = {
      standard = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/Small/hmpdroidgunship/textures/standard.png', 
    },
    Fac = {[7]=true},
    arcs = {fixed = { range=3, type = {'fullfront'}}},
    mesh = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships/Small/CIS_HMP_Gunship/HMP_GunshipBase.obj',
    moveSet = {'rs0','rbl1','bs1','rbr1','btl2','wbl2','bs2','wbr2','btr2','wtl3','rbl3','ws3','rbr3','wtr3','rs4','rs5'},
    keywords = {'Droid'},
    Config = {
      States = {
        [1] = {
            Name = "Stabalizers (Inactive)",
            Model = "https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/Small/hmpdroidgunship/HMP_GunshipStable.obj",
            ZRot = 0,
            Message = " deactivated their stabilizers.",
        },
        [2] = {
            Name = "Stabalizers (Active)",
            Model = "https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/Small/hmpdroidgunship/HMP_GunshipSlipping.obj",
            ZRot = 180,
            Message = " activated their stabilizers.",
        }
      },
      ContextText = "Toggle Stabilizers",
      Token = "http://nnxwing.com/Content/TTS/Config/HMPGunship.png"
    }
}

masterShipDB['eta2actis']={
    name = 'Eta-2 Actis',
    Hull = 3,
    Shield = 0,
    size = 'small',
    agi = 3,
    XWS = 'eta2actis',
    newSpawner = true,
    textures = {
      jedi = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/Small/eta2actis/textures/JediGeneral.jpg', 
      obi = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/Small/eta2actis/textures/standard.jpg', 
      anakin = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/Small/eta2actis/textures/standard.jpg', 
      aayla = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/Small/eta2actis/textures/standard.jpg', 
      shaak = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/Small/eta2actis/textures/standard.jpg', 
      yoda = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/Small/eta2actis/textures/standard.jpg', 
    },
    Fac = {[6]=true},
    arcs = {fixed = { range=3, type = {'front'}}},
    mesh = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/Small/eta2actis/eta2actis.obj',
    moveSet = {'wtl1','wtr1','wtl2','bbl2','bs2','bbr2','wtr2','ptl2t','ptr2t','wtl3','bbl3','bs3','bbr3','wtr3','bs4','rk4','ws5'},
    Config = {
      States = {
        [1] = {
            Name = "Normal",
            Model = nil,
            ZRot = 0,
            Message = " removed hyperspace ring,",
        },
        [2] = {
            Name = "Hyperspace ring mounted",
            Model = "https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships/Small/GRP_Hyperspace_Ring/hyperspace_ring_attachment.obj",
            ZRot = 180,
            Message = " mounted an hyperspace ring.",
        }
      },
      ContextText = "Mount/unmount hyperspace ring",
    }
}

masterShipDB['droidtrifighter']={
    name = 'Droid Tri-Fighter',
    Hull = 3,
    Shield = 0,
    size = 'small',
    agi = 3,
    XWS = 'droidtrifighter',
    newSpawner = true,
    textures = {
      standard = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/Small/droidtrifighter/textures/standard.png', 
    },
    Fac = {[7]=true},
    arcs = {fixed = { range=3, type = {'front'}}},
    mesh = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/Small/droidtrifighter/CIS_Tri-Fighter.obj',
    moveSet = {'rtl1t','wtl1','wtr1','rtr1t','btl2','wbl2','bs2','wbr2','btr2','btl3','wbl3','bs3','wbr3','btr3','rk3', 'bs4','ws5','rk5'},
    keywords = {'Droid'}
}

masterShipDB['tiewiwhispermodifiedinterceptor']={
    name = 'TIE/wi Whisper',
    Hull = 3,
    Shield = 2,
    size = 'small',
    agi = 2,
    XWS = 'tiewiwhispermodifiedinterceptor',
    newSpawner = true,
    textures = {
      standard = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/small/tiewiwhispermodifiedinterceptor/textures/standard.jpg',
    },
    Fac = {[5]=true},
    arcs = {fixed = { range=3, type = {'bullseye'}}, turret = {main = {name = 'primary', type= {'front', 'back'}}}},
    mesh = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/Small/tiewiwhispermodifiedinterceptor/TIE_Wi.obj',
    moveSet = {'wtl1','wtr1','wtl2','bbl2','bs2','bbr2','wtr2','rbl3s','wtl3','bbl3','bs3','bbr3','wtr3','rbr3s','bs4','rk4','bs5','rk5'},
    keywords = {'TIE'}
}

masterShipDB['tiesebomber']={
    name = 'TIE/se Bomber',
    Hull = 4,
    Shield = 2,
    size = 'small',
    agi = 2,
    XWS = 'tiesebomber',
    newSpawner = true,
    textures = {
      standard = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/small/tiewiwhispermodifiedinterceptor/textures/standard.jpg',
    },
    Fac = {[5]=true},
    arcs = {fixed = { range=3, type = {'front'}}},
    mesh = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/Small/tiesebomber/tie_se.obj',
    moveSet = {'rtl1','wbl1', 'bs1', 'wbr1', 'rtr1','wtl2','wbl2','bs2','wbr2','wtr2','rbl3s','wtl3','wbl3','bs3','wbr3','wtr3','rbr3s','ws4'},
    keywords = {'TIE'}
}

masterShipDB['btanr2ywing']={
    name = 'BTA-NR2 Y-Wing',
    Hull = 4,
    Shield = 3,
    size = 'small',
    agi = 1,
    XWS = 'btanr2ywing',
    newSpawner = true,
    textures = {
      plain = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/Small/dbtanr2ywing/textures/plain.png', 
      red = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/Small/dbtanr2ywing/textures/red.png', 
      blue = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/Small/dbtanr2ywing/textures/blue.png', 
      cai = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/Small/dbtanr2ywing/textures/caithrenalli.png', 
      corus = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/Small/dbtanr2ywing/textures/coruskapellim.png', 
      lega = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/Small/dbtanr2ywing/textures/legafossang.png', 
      teza = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/Small/dbtanr2ywing/textures/tezanasz.png', 
      wilsa = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/Small/dbtanr2ywing/textures/wilsateshlo.png', 
    },
    Fac = {[4]=true},
    arcs = {fixed = { range=3, type = {'front'}}},
    mesh =  'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/Small/btanr2ywing/RIS_Y-Wing.obj',
    moveSet = {'bbl1','bs1','bbr1','wtl2','wbl2','bs2','wbr2','wtr2','rtl3','wbl3','bs3','wbr3','rtr3','rs4','rk5'},
    keywords = {'Y-Wing'}
}

masterShipDB['gauntletfighter']={
  name = 'Gauntlet Fighter',
  newSpawner = true,
  Hull = 9,
  Shield = 2,
  size = 'large',
  agi = 2,
  ProximityHider = true,
  XWS = 'gauntletfighter',
  Fac = {[1]=true,[2]=true,[3]=true,[6]=true,[7]=true},
  arcs = {fixed = { range=3, type = {'frontback'}}},
  textures = {
    bokatan = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/large/gauntletfighter/textures/BoKatan.jpg',
    bokatancis = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/large/gauntletfighter/textures/BoKatanCIS.jpg',
    deathwatch = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/large/gauntletfighter/textures/Deathwatch.jpg',
    default = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/large/gauntletfighter/textures/Default.jpg',
    imperial = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/large/gauntletfighter/textures/Imperial.jpg',
    maul = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/large/gauntletfighter/textures/Maul.jpg',
    plain = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/large/gauntletfighter/textures/Plain.jpg',
    previzsla = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/large/gauntletfighter/textures/PreVizla.jpg',
    scum = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/large/gauntletfighter/textures/ScumColours.jpg'
  },
  moveSet = {'bbl1','bbr1','wtl2','bbl2','bs2','bbr2','wtr2','rtl3','wbl3','ws3','wbr3','rtr3','ws4','rs0'},
  mesh = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/large/gauntletfighter/ship-base.obj',
  Config = {
    States = {
      [1] = {
          Name = "Swivel Wing (Down)",
          Model = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/large/gauntletfighter/wings-normal.obj',
          ZRot = 0,
          Message = " lowered their swivel wing.",
      },
      [2] = {
          Name = "Swivel Wing (Up)",
          Model = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/large/gauntletfighter/wings-pivot.obj',
          ZRot = 0,
          Message = " raised their swivel wing.",
      }
    },
    ContextText = "Rise/lower swivel wing",
    Token = "http://nnxwing.com/Content/TTS/Config/GauntletFighter.png"
    }
}

masterShipDB['st70assaultship']={
  name = 'ST-70 Assault Ship',
  newSpawner = true,
  textures = {
    guildbountyhunter = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/medium/st70assaultship/textures/guildbountyhunter.jpg',
    mandalorian = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/medium/st70assaultship/textures/mandalorian.png',
    plain = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/medium/st70assaultship/textures/plain.jpg',
  },
  Hull = 7,
  Shield = 2,
  size = 'medium',
  agi = 2,
  XWS = 'st70assaultship',
  Fac = {[3]=true},
  arcs = {fixed = { range=3, type = {'front'}}},
  moveSet = {'rtl1','wbl1','bs1','wbr1','rtr1','rtl2t','wtl2','wbl2','bs2','wbr2','wtr2','rtr2t','rtl3','wbl3','bs3','wbr3','rtr3','bs4','rk5','rs0'},
  mesh = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/medium/st70assaultship/razorcrest.obj',
}


-- Huge ships
masterShipDB['cr90corvette']={
    name = 'CR-90 Corvette',
    XWS = 'cr90corvette',
    Hull = 18,
    Shield = 7,
    Energy = 7,
    size = 'huge',
    agi = 0,
    mountingPoints = { front = {0, -2.63}, rear = {0, 2.63} },
    Fac = {[1]=true, [6]=true},
    arcs = {fixed = { range=4, type = {'leftright'}}},
    moveSet = {'rbl0','rs0','rbr0','wbl1','ws1','wbr1','bbl2','bs2','bbr2','rbl3','bs3','rbr3','rs4','rs5'},
    mesh = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/Huge/CR90%20Corvette/CR90%20Corvette.obj',
    keywords = {'Corvette'}
  }

masterShipDB['croccruiser']={
    name = 'C-ROC Cruiser',
    XWS = 'croccruiser',
    Hull = 12,
    Shield = 4,
    Energy = 4,
    size = 'huge',
    agi = 0,
    mountingPoints = { front = {0, -2.63}, rear = {0, 2.63} },
    Fac = {[3]=true, [7]=true},
    arcs = {fixed = { range=3, type = {'front'}}},
    moveSet = {'rbl0','rs0','rbr0','wbl1','bs1','wbr1','wbl2','bs2','wbr2','rbl3','ws3','rbr3','rs4','rs5'},
    mesh = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/Huge/CR0C/CR0C%20Cruiser.obj',
    keywords = {'Cruiser'}
  }

masterShipDB['gozanticlasscruiser']={
    name = 'Gozanti-class Cruiser',
    XWS = 'gozanticlasscruiser',
    Hull = 11,
    Shield = 5,
    Energy = 3,
    size = 'huge',
    agi = 0,
    mountingPoints = { front = {0, -2.05}, rear = {0, 2.05} },
    Fac = {[2]=true, [5]=true},
    arcs = {fixed = { range=3, type = {'front'}}},
    moveSet = {'rbl0','rs0','rbr0','wbl1','bs1','wbr1','rbl2','bs2','rbr2','bs3','rs4'},
    mesh = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/Huge/Gozanti-Class%20Cruiser/Gozanti-Class%20Cruiser.obj',
    keywords = {'Cruiser'}
  }

masterShipDB['gr75mediumtransport']={
    name = 'GR-75 Medium Transport',
    XWS = 'gr75mediumtransport',
    Hull = 12,
    Shield = 3,
    Energy = 4,
    size = 'huge',
    agi = 0,
    mountingPoints = { front = {0, -2.05}, rear = {0, 2.05} },
    Fac = {[1]=true, [4]=true},
    arcs = {fixed = { range=3, type = {'front'}}},
    moveSet = {'rbl0','rs0','rbr0','bbl1','bs1','bbr1','wbl2','ws2','wbr2','rs3','rs4'},
    mesh = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/Huge/GR-75%20Transport/GR-75%20Transport.obj',
    keywords = {'Freighter'}
}

masterShipDB['raiderclasscorvette']={
    name = 'Raider-class Corvette',
    XWS = 'raiderclasscorvette',
    Hull = 20,
    Shield = 8,
    Energy = 6,
    size = 'huge',
    agi = 0,
    mountingPoints = { front = {0, -2.63}, rear = {0, 2.63} },
    Fac = {[2]=true, [5]=true},
    arcs = {fixed = { range=3, type = {'fullfront'}}},
    moveSet = {'rbl0','rs0','rbr0','bbl1','ws1','bbr1','wbl2','bs2','wbr2','rbl3','bs3','rbr3','ws4','rs5'},
    mesh = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/Huge/Raider%20Class%20Corvette/Raider%20Class%20Corvette.obj',
    keywords = {'Corvette'}
  }

  masterShipDB['tridentclassassaultship']={
      name = 'Trident-class Assault Ship',
      XWS = 'tridentclassassaultship',
      Hull = 10,
      Shield = 4,
      Energy = 3,
      size = 'huge',
      agi = 0,
      mountingPoints = { front = {0, -2.63}, rear = {0, 2.63} },
      Fac = {[3]=true, [7]=true},
      arcs = {fixed = { range=3, type = {'front'}}},
      moveSet = {'rs0','rbl0','rbr0','bbl2','bs2','bbr2','wbl3','bs3','wbr3','bs4','rk4','ws5','ws1r','rs2r'},
      mesh = 'https://raw.githubusercontent.com/JohnnyCheese/TTS_X-Wing2.0/master/assets/ships-v2/Huge/TridentClass/Trident-Class_temp.obj',
      keywords = {'Assault Ship'}
    }

  return masterShipDB
